---
title: "group11a_Chlebowy_Shane_Sumbission_file"
output: html_document
date: "2025-12-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading in our scoring data + best model
```{r}
scoring = readRDS('scoring.rds')

# XGBoost was our best performing model, with the highest reported F1 score
best_model = readRDS('best_xgb.rds')
```

# Making predictions
```{r}
# Get predicted probabilities for "Yes"
y_prob <- predict(best_model, newdata = scoring, type = "prob")[, "Yes"]

# Apply custom threshold (0.07) -- Our optimum threshold for xgb model 6c
threshold <- 0.07
y_pred <- ifelse(y_prob >= threshold, 1, 0)

# Convert to factor with correct level order
y_pred <- factor(y_pred, levels = c(0, 1))

# Combine predictions with IDs
predictions <- data.frame(ID = scoring$ID, loan_status = y_pred)

# Check distribution
table(predictions$loan_status)

# Write to CSV (uncomment to save)
 write.csv(predictions, "group11a_Chlebowy_Shane_submission_file.csv", row.names = FALSE)

```